version: 1
from: "ghcr.io/nfra-project/kickstart-flavor-php:8.1"


packages: [php8.1-curl, php8.1-http, php8.1-raphf, php8.1-mbstring, nginx]


config_file:
  template: "config.php.dist"
  target: "config.php"

command:
  build:
    - "sudo apt-get update && sudo apt-get upgrade -y"
    - "composer update"

  run:
    - "sudo php -f bin/ingress_hypervise.php"
  dev:

  test:

